name: Build and Test .NET API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Kodni olish
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. .NET SDK o‘rnatish
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x   # Sizning loyihangiz .NET 8 bo‘lsa

      # 3. Dependencies yuklab olish
      - name: Restore dependencies
        run: dotnet restore JwtApi/JwtApi.csproj

      # 4. Loyihani build qilish
      - name: Build
        run: dotnet build JwtApi/JwtApi.csproj --no-restore --configuration Release

      # 5. Test (agar testlar bo‘lsa)
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Docker build
      - name: Build Docker image
        run: docker build -t jwtapi:latest .

      # Agar DockerHub yoki GitHub Packages ga push qilmoqchi bo‘lsangiz
      # Docker login qilish va push qo‘shiladi
